name: flutter_app_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.4
  fluttertoast: ^8.2.8
  flutter_easyloading: ^3.0.5
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  path_provider: ^2.1.4
  http: ^1.2.2
  flutter_lints: ^4.0.0
  curved_navigation_bar: ^1.0.6
  network_info_plus: ^6.0.1
  socket_io_client: ^2.0.3+1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  equatable: ^2.0.5
  auto_size_text: ^3.0.0
  lottie: ^3.1.2
  diacritic: ^0.1.5
  google_fonts: ^6.2.1
  logger: ^2.4.0
#  youtube_player_flutter: ^9.0.3
  page_transition: ^2.1.0
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  flutter_spinkit: ^5.2.1
  throttling: ^2.0.1
  flutter_speed_dial: ^7.0.0
  image_picker: ^0.8.4+4




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  json_serializable: ^6.8.0




flutter:
  uses-material-design: true
  assets:
    - assets/images/

